[package]
name = "bfg-prolog"
version = "0.4.0"
authors = ["Ebrahim Azarisooreh <ebrahim.azarisooreh@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
lalrpop = "0.17.1"
lalrpop-util = "0.17.1"
regex = "1.1.9"
