[package]
name = "bfg-prolog"
version = "0.1.0"
authors = ["Ebrahim Azarisooreh <ebrahim.azarisooreh@gmail.com>"]
edition = "2018"

[dependencies]
#simple_logger = "1.3.0"
env_logger = "0.6.2"
log = "0.4.6"