[package]
name = "bfg-prolog"
version = "0.1.0"
authors = ["Ebrahim Azarisooreh <ebrahim.azarisooreh@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
env_logger = "0.6.2"
log = "0.4.6"
lalrpop = "0.17.1"
lalrpop-util = "0.17.1"
regex = "1.1.9"
